---
image: php:7.1

stages:
  - test_build
  - test

test_build:
  stage: test_build
  script:
    - bash ci/docker_install.sh > /dev/null
    - php /usr/local/bin/composer install --no-interaction --no-progress

phpunit-tests:
  stage: test
  dependencies:
    - test_build
  script:
    - php vendor/bin/phpunit

phpcs:
  stage: test
  dependencies:
    - test_build
  script:
    - php vendor/bin/phpcs --standard=PSR2 src/ bin/ hooks/ tests/
