---
image: php:7.1

before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null

test:app:
  script:
  - php /usr/local/bin/composer install --no-interaction --no-progress
  - php vendor/bin/phpunit
