language: php

php:
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

# Only run tests when master branch changes or when a PR branch is updated.
branches:
  only:
  - master

before_script:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpcs --colors --standard=PSR2 src/ bin/ hooks/ tests/
  - php vendor/bin/phpunit --coverage-text
  - bin/git-review tools:php-cs-fixer

matrix:
  fast_finish: true